### ISSUE TITLE
[Feature] - Miranum Connect to support FitConnect as integration

### ISSUE THREAD

**Issue by Hafflgav** [FlowSquad/miranum#49]
- [x] Description created 
- [x] Reviewed by peer (24 hr window): <tag-person-here>
- [x] Prioritised

# Description 
- A process can be started with data coming from FitConnect 
- We can be configured which port can start a process. 
- We have a test-environment in FitConnect which allows local development 

## Sub-Tasks 
```[tasklist]
### Tasks
- [x] Create Account in FitKo test environment
- [x] FitKo as miranum integration to start process instance
- [x] Fitconnect Client generation
- [x] Via env in miranum integration: Create mapping between process and fit connect port
- [x] Develop test-data generator which adds data to the fit connect ports
- [x] Create documentation
- [ ] Add to miranum docs
```
