### ISSUE TITLE
[Feature] - Create Element Template Generator for Camunda 7

### ISSUE THREAD

**Issue by Hafflgav** [FlowSquad/miranum#51]
- [x] Description created 
- [x] Reviewed by peer (24 hr window): <tag-person-here>
- [x] Prioritised

# Description 
As a developer I want to generate Element Templates from code to increase the reusability of the integrations I have written. This should be possible via a simple maven or gradle dependency. It saves me time not to create the JSON templates by myself and have them generated. 
This should apply for Camunda Platform 7. 

## Sub-Tasks 

```[tasklist]
### Tasks
- [x] Draft a prototype
- [x] Write test cases
- [x] Refactor
- [x] Create documentation


```
```[tasklist]
### Post-merge tasks
- [ ]  Release as maven or gradle dependency
- [ ] Extend miranum-docs
```

**Comment by rami-nk** [comment]
![Image](https://user-images.githubusercontent.com/58343300/224018434-a9ed7720-ce3e-4afe-8795-84a9358e2fd5.png)

**Comment by rami-nk** [comment]
@dominikhorn93 The schema Camunda provides is not a json schema, but acts as container for json schemas inside the definitions property. How do we want to go about generating the pojos?

**Comment by dominikhorn93** [comment]
https://unpkg.com/@camunda/element-templates-json-schema@0.1.0/resources/schema.json from https://github.com/camunda/element-templates-json-schema is a json schema or do I miss something? You should be able to generate pojos from that with https://github.com/joelittlejohn/jsonschema2pojo

**Comment by rami-nk** [comment]
Ok yeah got it, somehow the versions after 0.2.0 are schema container
