### ISSUE TITLE
[Research] - Research on Element Template Generation

### ISSUE THREAD

**Issue by Hafflgav** [FlowSquad/miranum#53]
- [x] Description created 
- [x] Reviewed by peer (24 hr window): <tag-person-here>
- [x] Prioritised

# Description 
As a developer I want to generate Element Templates from code to increase the reusability of the integrations I have written. This should be possible via a simple maven or gradle dependency. It saves me time not to create the JSON templates by myself and have them generated. 
This should apply for Camunda Platform 7 and 8. 
This research task is being used to gain a basic understanding of element templates and how to generate them from existing code.

## Sub-Tasks 

```[tasklist]
### Tasks
- [x] Do some research on Element (Connector) Templates (similar solutions, difference C7 and C8)
- [x] Find out the most intuitive way how such a generator can be included in dev projects
```

**Comment by rami-nk** [comment]
My thoughts on this: 

![Image](https://user-images.githubusercontent.com/58343300/223398183-8fe5c689-f598-41fb-bab4-a4322c6057ec.svg)

**Comment by Hafflgav** [comment]
@rami-nk your proposal sounds pretty good to me. 
As you have said correctly - given the separation of concerns adding a new annotation for generating element templates makes perfectly sense. 🚀

**Comment by dominikhorn93** [comment]
@rami-nk sounds good to me. One thing is missing -> Result should be added as OutputParameter.
Moreover you could generate the element template java classes from the camunda element template json schema.

If we have nested classes only the property name in the root object is important.
Nested properties cannot be considered.

Maybe we should take a close look at how to handle json data in processes and make mapping easier. But this would be another epic.

**Comment by Hafflgav** [comment]
FYI: 
Currently there is no project which does a similar thing. 

The latest supported [[Camunda element templates JSON Schema versions](https://github.com/camunda/element-templates-json-schema)](https://github.com/camunda/element-templates-json-schema) are

- `v0.10.0` (Camunda Platform 7)
- `v0.5.0` (Camunda Platform 8)

**Comment by rami-nk** [comment]
> @rami-nk sounds good to me. One thing is missing -> Result should be added as OutputParameter. Moreover you could generate the element template java classes from the camunda element template json schema.
> 
> If we have nested classes only the property name in the root object is important. Nested properties cannot be considered.
> 
> Maybe we should take a close look at how to handle json data in processes and make mapping easier. But this would be another epic.

Ok thank you. But generating java classes from the camunda element template json schema is also another story that has to be defined. The scope of this epic is just the other way, namely generating element templates form code. And everything for now should be modeled as an input, right?

**Comment by dominikhorn93** [comment]
@rami-nk yes the scope is to generated templates from code. But if we implement that in Java it would be nice to have the  corresponding java classes in which the input / output should be mapped. You could generate the classes from the json schema definition Camunda provides.

**Comment by rami-nk** [comment]
@dominikhorn93 Oh yess I got that point. I actually tried yesterday to generate the c7 elmenet template class with https://github.com/joelittlejohn/jsonschema2pojo but it seems like it does have problems with big json schemas. I have to further look into it today
