### ISSUE TITLE
[Feature] Add templates for Epics and Features

### ISSUE THREAD

**Issue by Hafflgav** [FlowSquad/miranum#54]
- [x] Description created 
- [x] Reviewed by peer (24 hr window): <tag-person-here>
- [x] Prioritised

# Description 
We need issue templates for epics and features in the docs, miranum and miranum-ide repository. 

## Sub-Tasks 

```[tasklist]
### Tasks
- [x] Create issue templates in the Miranum Repository
- [x] Create issue templates in the Miranum-IDE Repository
- [x] Create issue templates in the Miranum-Docs Repository
```
