### ISSUE TITLE
[Feature] - Element Template Generation for Messages (C8 & C7) 

### ISSUE THREAD

**Issue by Hafflgav** [FlowSquad/miranum#88]
- [x] Description created
- [ ] Reviewed by peer: @dominikhorn93 
- [ ] Prioritised

# Description
Element Templates should not only be generated for worker annotations but for messages as well. 
E.g. when a domain event is thrown we want to be able to use an annotation to generate an element template on build which can be applied to a process diagram. With this functionality I can trigger other process and intermediate events when such domain event is thrown from an application. 

## Sub-Tasks
 
```[tasklist]
### Tasks
- [ ] Generate Element-Template for Messages compatible with Camunda 7 
- [ ] Generate Element-Templates for Messages compatible with Camunda 7 
- [ ] Create an example project 
- [ ] Document feature 
```

**Comment by DaAnda97** [comment]
@dominikhorn93 @Hafflgav  is this still a relevant feature?

**Comment by lmoesle** [comment]
> [@dominikhorn93](https://github.com/dominikhorn93) [@Hafflgav](https://github.com/Hafflgav) is this still a relevant feature?

I will close this issue. In case this is still relevant please open the issue again
